[project]
name = "smartreflect"
version = "0.1.0"
description = "Smartphone usage visualization and analysis webapp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]>=0.136.1",
  "pandas>=3.0.2",
  "pysqlite3>=0.6.0",
]

[config]
dataset_path = "data/dataset.csv"
database_path = "backend/db/database.db"
